// data/mockProblems.js
export const MOCK_PROBLEMS = [
  {
    id: 1,
    code: "QA-1001",
    title: "옴의 법칙을 이용하여 전류를 구하시오",
    difficulty: "입문",
    concept: "회로이론",
    time: 5,
    status: "UNSOLVED",
    isCorrect: null,
  },
  {
    id: 2,
    code: "QA-1002",
    title: "직렬 회로에서 전체 저항값 계산",
    difficulty: "초급",
    concept: "회로이론",
    time: 7,
    status: "SOLVED",
    isCorrect: true,
  },
  {
    id: 3,
    code: "QA-1003",
    title: "병렬 회로의 전압 분배 계산",
    difficulty: "초급",
    concept: "회로이론",
    time: 8,
    status: "INCORRECT",
    isCorrect: false,
  },
  {
    id: 4,
    code: "QA-1004",
    title: "키르히호프 전류 법칙(KCL) 적용 문제",
    difficulty: "중급",
    concept: "회로이론",
    time: 10,
    status: "UNSOLVED",
    isCorrect: null,
  },
  {
    id: 5,
    code: "QA-1005",
    title: "키르히호프 전압 법칙(KVL) 계산",
    difficulty: "중급",
    concept: "회로이론",
    time: 12,
    status: "SOLVED",
    isCorrect: true,
  },
  {
    id: 6,
    code: "QA-1006",
    title: "전력(P=VI) 계산 문제",
    difficulty: "입문",
    concept: "전력",
    time: 6,
    status: "UNSOLVED",
    isCorrect: null,
  },
  {
    id: 7,
    code: "QA-1007",
    title: "3상 전력 계산 공식 적용",
    difficulty: "중급",
    concept: "전력",
    time: 14,
    status: "INCORRECT",
    isCorrect: false,
  },
  {
    id: 8,
    code: "QA-1008",
    title: "유도 전동기의 원리 설명",
    difficulty: "고급",
    concept: "전기기기",
    time: 15,
    status: "SOLVED",
    isCorrect: true,
  },
  {
    id: 9,
    code: "QA-1009",
    title: "변압기 효율 계산",
    difficulty: "중급",
    concept: "전기기기",
    time: 13,
    status: "UNSOLVED",
    isCorrect: null,
  },
  {
    id: 10,
    code: "QA-1010",
    title: "단상 회로 역률 계산",
    difficulty: "초급",
    concept: "전력",
    time: 9,
    status: "INCORRECT",
    isCorrect: false,
  },
];
